export const SplOfferData = [
    {
      _id: "201",
      img: imprimante1,
      productName: "imprimante",
      price: "35.00",
      color: "Blank and White",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "imprimante",
    },
    {
      _id: "202",
      img: imprimante2,
      productName: "imprimante",
      price: "180.00",
      color: "Gray",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "imprimante",
    },
    {
      _id: "203",
      img: imprimante4,
      productName: "imprimante",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "imprimante",
    },
    {
      _id: "204",
      img: imprimante5,
      productName: "imprimante",
      price: "220.00",
      color: "Black",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "imprimante",
    },
    {
      _id: "205",
      img: imprimante6,
      productName: "imprimante",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "imprimante",
    },
    {
      _id: "206",
      img: imprimante7,
      productName: "imprimante",
      price: "220.00",
      color: "Black",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "imprimante",
    },
    {
      _id: "207",
      img: imprimante8,
      productName: "imprimante",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "imprimante",
    },
    {
      _id: "208",
      img: imprimante9,
      productName: "imprimante",
      price: "220.00",
      color: "Black",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "imprimante",
    },
    {
      _id: "209",
      img: encre1,
      productName: "encre",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "ancre",
    },
    {
      _id: "210",
      img: encre2,
      productName: "encre",
      price: "220.00",
      color: "Black",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "ancre",
    },
    {
      _id: "211",
      img: encre3,
      productName: "encre",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "ancre",
    },
    {
      _id: "212",
      img: encre4,
      productName: "encre",
      price: "220.00",
      color: "Black",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "ancre",
    },
    {
      _id: "213",
      img: ruban1,
      productName: "Ruban",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "Ruban",
    },
    {
      _id: "214",
      img: ruban2,
      productName: "Ruban",
      price: "220.00",
      color: "Black",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "Ruban",
    },
    {
      _id: "215",
      img: ruban3,
      productName: "Ruban",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "Ruban",
    },
    {
      _id: "216",
      img: ruban4,
      productName: "Ruban",
      price: "220.00",
      color: "Black",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "Ruban",
    },
    {
      _id: "217",
      img: bac1,
      productName: "Bac de dechet",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "Bac",
    },
    {
      _id: "219",
      img: bac2,
      productName: "Bac de dechet",
      price: "220.00",
      color: "Black",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "Bac",
    },
    {
      _id: "220",
      img: bac3,
      productName: "Bac de dechet",
      price: "25.00",
      color: "Mixed",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "Bac",
    },
    {
      _id: "221",
      img: bac4,
      productName: "Bac de dechet",
      price: "220.00",
      color: "Black",
      badge: true,
      des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
      cat: "Bac",
    },
  ];